version: '3'

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=password123
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PORT_NUMBER=7000
    ports:
      - '7000:7000'
    networks:
      - appnetwork
    volumes:
      - 'redis_data:/bitnami/redis/data'

networks:
  appnetwork:
    driver: bridge
volumes:
  redis_data:
    driver: local